
mybatis:
  configuration:
    map-underscore-to-camel-case: true

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    password: abcd1234
    url: jdbc:mariadb://database-1.czzavqlpg4tl.ap-northeast-2.rds.amazonaws.com:3306/green
    username: nowon
